services:
  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=anxo_root
      - MYSQL_DATABASE=wp_db
      - MYSQL_USER=anxo_user
      - MYSQL_PASSWORD=anxo_pass
    expose:
      - 3306
      - 33060
  wordpress:
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html
    ports:
      - 8080:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=anxo_user
      - WORDPRESS_DB_PASSWORD=anxo_pass
      - WORDPRESS_DB_NAME=wp_db
volumes:
  db_data:
  wp_data: